- id: '1603219085262'
  alias: Write Servo Value to ESP
  trigger:
    platform: state
    entity_id: sensor.tv_tid_servo_control
  action:
    - service: esphome.tv_servo_control_control_servo
      data_template:
        level: '{{ trigger.to_state.state | int }}'
